[package]
name = "radio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ['rodio']
mpv = []
rodio = ["dep:rodio", "dep:reqwest"]

[dependencies]
actix-web = "4.1.0"
tokio = { version = "1.21.0", features = ["full"] }

# Rodio backend
reqwest = { version = "0.11.11", default-features = false, features = ["rustls", "stream"], optional = true }
rodio = {version = "0.15.0", optional = true}
bytes = "1.2.1"
futures-util = "0.3.24"
