[package]
name = "radio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ['rodio']
mpv = []
rodio = [
    "dep:reqwest",
    "dep:rodio",
    "dep:bytes",
    "dep:futures-util",
    "dep:rustls",
]

[dependencies]
actix-web = "4.1.0"
tokio = { version = "1.21.0", features = ["full"] }

# Rodio backend
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls", "stream"], optional = true}
rodio = { version = "0.15.0", optional = true}
bytes = { version="1.2.1", optional = true}
futures-util = { version="0.3.24", optional=true}
rustls = { version = "0.20.6", optional = true }
