[package]
name = "radio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ['rodio']
mpv = []
rodio = []

[dependencies]
actix-web = "4.1.0"
reqwest = { version = "0.11.11", default-features = false, features = ["rustls", "stream"] }
rodio = "0.15.0"
tokio = { version = "1.21.0", features = ["full"] }

