port = 8083
session_key = "my_secret_session_key_which_must_be_over_64_characters_in_length"

[[users]]
username = "admin"
password = "secret"

[[stations]]
id = "example"
name = "Example Radio"
description = "This is an example radio"
url = "https://example.com/stream"
image_file = "example.png"
auto_restart = true
