### SERVER CONFIG ###
port = 8083
session_key = "my_secret_session_key_which_must_be_over_64_characters_in_length"

### USERS ###
[[users]]
username = "admin" # A unique username
password = "secret" # A secure password

[[users]]
username = "another"
password = "secret2"

### STATIONS ###

[[stations]]
id = "example" # An arbitrary (unique) ID for the stream
name = "Example Radio" # A user-friendly name
description = "This is an example radio" # A user-friendly description
url = "https://example.com/stream" # The MP3 source of the stream
image_file = "example.png" # The image file inside the `image` directory
auto_restart = true # Whether the stream should be restarted if it stops of fails
auto_start = false # Whether the stream should play as soon as the service is launched
